### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by Tim2309** [volca/homebridge-esplock#4]
I use the esp Lock Plugin with 2 „locks“ 
If both are on everything is fine, but in my case one lock isn‘t powered the whole time.
In this case the homebridge server got an error (Screenshot)
![img_1509](https://user-images.githubusercontent.com/30231962/28264554-c08a0606-6aeb-11e7-84b5-5134c71354b6.PNG)

**Comment by volca** [comment]
I made minor changes for code but not test. Please try it.

**Comment by Tim2309** [comment]
Thanks for the quick response, but i think the Problem still exist with the Update.
The esp8266 „Pumpe“ is switched at the moment.
![img_1515](https://user-images.githubusercontent.com/30231962/28301423-c60559c8-6b86-11e7-8bcd-0a5d1820f3e8.PNG)

**Comment by Tim2309** [comment]
Sorry i made a mistake with the update, but still the same Problem, here is a new screenshot 

![img_1516](https://user-images.githubusercontent.com/30231962/28301698-d8631f86-6b88-11e7-873b-7d7a2e93edee.PNG)

**Comment by volca** [comment]
Hello,

I update the library again. Please check it.

Thank you

**Comment by Tim2309** [comment]
Now i got a new error
![img_1518](https://user-images.githubusercontent.com/30231962/28302245-7b97e40e-6b8c-11e7-9d69-aa3db4c561cd.PNG)

**Comment by volca** [comment]
Thank you for your patient. I updated the package again. Now removed the log.

**Comment by Tim2309** [comment]
Looks better but now it crash at the Battery status 
![img_1519](https://user-images.githubusercontent.com/30231962/28303332-ea0058da-6b92-11e7-8ed3-23618789605f.PNG)

**Comment by volca** [comment]
Library updated. I think it's ok now.

**Comment by Tim2309** [comment]
I think it work, thank you for your great work

**Comment by volca** [comment]
Thanks for your confirm
