### ISSUE TITLE
battery indicator

### ISSUE THREAD

**Issue by unitede** [volca/homebridge-esplock#5]
hello, is it possible to remove the battery indicator, it shows all the time the battery is low.
In my case the lock is powered with a 5v power supply and i don't need the indicator.
It would also be good if the battery will show 100%.

**Comment by volca** [comment]
Please edit your sketch and add a field for battery level, see [this line](https://github.com/AprilBrother/ESPea-Examples/blob/master/examples/04.Network/http-lock/http-lock.ino#L23)

Change it to

```
    sprintf(rsp, "{\"state\":\"%s\",\"statusCode\":200,\"battery\":100}", digitalRead(RELAY_PIN) ? "unlocked" : "locked");

```

**Comment by unitede** [comment]
Thank you, works fine!

**Comment by volca** [comment]
Great. So I closed the issue.
