### ISSUE TITLE
"Battery Low" yet 100% shown

### ISSUE THREAD

**Issue by macmonty** [volca/homebridge-esplock#7]
Hi, my esp8266 doorlock in are showing low battery in Home while simultaneously showing 100% battery. I'm not sure I trust that 100% but I don't know how to independently verify what's accurate.

**Comment by volca** [comment]
Yes. the sketch writes hard code 100% battery level. You can modify it to measure battery level and get  accurate value. 

Please check [the document](https://arduino-esp8266.readthedocs.io/en/latest/libraries.html#esp-specific-apis) for `ESP.getVcc()`

**Comment by macmonty** [comment]
I think this is not the issue, the esp reports 100 % battery level (checked by http response), but in my iphone the device shows icon of low level battery
![captura de pantalla 2018-08-13 a las 9 00 03](https://user-images.githubusercontent.com/2550897/44017119-8308fc3a-9ed7-11e8-86a6-a0ba85d78fe6.png)
![captura de pantalla 2018-08-13 a las 8 59 45](https://user-images.githubusercontent.com/2550897/44017123-87ac5624-9ed7-11e8-824e-a407739bfbc6.png)

**Comment by volca** [comment]
Could you please show the sketch for esp8266? see [the issue](https://github.com/volca/homebridge-esplock/issues/5) also

**Comment by macmonty** [comment]
Thanks problem solved, runs like a charm!!

**Comment by volca** [comment]
Thanks for confirming. I've also modified this line in that sketch
